# Generated by Django 5.1.7 on 2025-03-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('work', 'work'), ('personal', 'personal'), ('study', 'study'), ('other', 'other')], max_length=20)),
                ('due_date', models.DateField()),
            ],
        ),
    ]
